### ISSUE TITLE
Merging data with several raw files per CoBo: re-ordering of text file

### ISSUE THREAD

**Issue by clsantama** [ATTPC/ATTPCROOTv2#17]
Issue of file ordering when using a .txt file to merge graw data with several files per CoBo
Need to re-write the shell script ([here](https://github.com/ATTPC/ATTPCROOTv2/blob/develop/macro/Unpack_GETDecoder2/runfiles/create_runfile.sh) or [there](https://github.com/ATTPC/ATTPCROOTv2/blob/develop/macro/Unpack_GETDecoder2/runfiles/NSCL/alphas/create_runfile.sh)) to correctly order the file names

**Comment by clsantama** [comment]
For tryout, can use the alpha scattering data available on the fishtank (run 0085) with the shell script create_runfile.sh:

> ./create_runfile.sh alpha_run_0085 /mnt/analysis/attpcroot/data_alphas/run0085/

One can also use my personal space to work on this:
     > cd /projects/attpcroot/santamar/ATTPCROOTv2/
     > source build/config.sh
     > cd macro/perso/runfiles_alphas/
     > ./create_runfile.sh alpha_run_0085 /mnt/analysis/attpcroot/data_alphas/run0085/
     > cd ../
     > root 'run_unpack_alpha.C("0085")'

**Comment by Yassid** [comment]
Two important notes:

We have two versions of the DAQ. In the former, data was structured by CoBos (10 in total). The new DAQ creates one file per Asad (40) in total. The scripts must be somewhat different. The analysis macros have to reflect also the number of CoBos.

In addition, the macro has to stop the process if the files are to found. This is not done in every macro (but in few) and it leads to memory leak. A related problem is that sometimes, when the end of file is reached, the program does not stop. We need to implement an exit function when this happens. This happens when we use the RunOnTB mode which does each task until the end of the file is found. With the Run function (and specifying the number of events) this issue does not appear. But one needs to know the number of events before hand. This is possible with a module developed by Genie Jhang (we should contact him).

**Comment by clsantama** [comment]
New python script that solves this problem here: [https://github.com/ATTPC/ATTPCROOTv2/blob/develop/macro/Unpack_GETDecoder2/runfiles/NSCL/e17504/listfiles.py](https://github.com/ATTPC/ATTPCROOTv2/blob/develop/macro/Unpack_GETDecoder2/runfiles/NSCL/e17504/listfiles.py)
Might write a bash script later on more general that would work for most cases in the future.
